#!/bin/bash

cd $(dirname $0)
. ./colors

packages=(
  # Development
  'default-jdk'
  'git'
  'make'
  'nim'
  'openssl'
  'ruby'
  'vim'
)

echo "${CYAN}Starting apt install.${RESET}"
for e in ${packages[@]}; do
  sudo apt install -y ${e}
done
echo "${CYAN}Starting apt update.${RESET}"
sudo apt update
echo "${CYAN}Starting apt upgrade.${RESET}"
sudo apt upgrade -y
